[[builder]]
name = "aarch64_builder"
tags = ["builder"]
[builder.config]
type = "Aws"
params.region = "us-east-2"
params.instance_type = "c7g.2xlarge"
params.ami_id = "ami-06fdde90cf1861127"
params.subnet_id = "subnet-02ae5ad480eacc4bc"
params.key_pair_name = "komodo-key"
params.assign_public_ip = true
params.security_group_ids = ["sg-0babe545ecfb49c9b"]
params.user_data = """
#!/bin/bash
curl -sSL https://raw.githubusercontent.com/mbecker20/komodo/main/scripts/setup-periphery.py | HOME=/root python3"""

##

[[builder]]
name = "x86_builder"
tags = ["builder"]
[builder.config]
type = "Aws"
params.region = "us-east-2"
params.ami_id = "ami-0364d0950b88ef0e9"
params.subnet_id = "subnet-02ae5ad480eacc4bc"
params.key_pair_name = "komodo-key"
params.assign_public_ip = true
params.security_group_ids = ["sg-0babe545ecfb49c9b"]
params.user_data = """
#!/bin/bash
curl -sSL https://raw.githubusercontent.com/mbecker20/komodo/main/scripts/setup-periphery.py | HOME=/root python3"""

##

[[resource_sync]]
name = "builders"
tags = ["builder"]
[resource_sync.config]
git_provider = "git.komo.do"
repo = "komodo/build"
git_account = "mbecker20"
resource_path = ["builders.toml"]
managed = true
match_tags = ["builder"]