[[build]]
name = "komodo-binaries-dev-aarch64"
tags = ["dev", "binaries", "aarch64"]
[build.config]
builder = "aarch64-builder"
version = "1.16.12"
auto_increment_version = false
image_name = "binaries"
image_tag = "dev-aarch64"
links = [
  "https://git.komo.do/komodo/-/packages/container/binaries"
]
repo = "mbecker20/komodo"
branch = "1.16.12"
dockerfile_path = "bin/binaries.Dockerfile"
image_registry.domain = "git.komo.do"
image_registry.account = "mbecker20"
image_registry.organization = "komodo"

##

[[build]]
name = "komodo-binaries-dev-x86_64"
tags = ["dev", "binaries", "x86_64"]
[build.config]
builder = "x86_64-builder"
version = "1.16.12"
auto_increment_version = false
image_name = "binaries"
image_tag = "dev-x86_64"
links = [
  "https://git.komo.do/komodo/-/packages/container/binaries"
]
repo = "mbecker20/komodo"
branch = "1.16.12"
dockerfile_path = "bin/binaries.Dockerfile"
image_registry.domain = "git.komo.do"
image_registry.account = "mbecker20"
image_registry.organization = "komodo"

##

[[build]]
name = "komodo-core-dev"
tags = ["dev", "core"]
[build.config]
builder = "x86_64-builder"
version = "1.16.12"
auto_increment_version = false
image_name = "core"
image_tag = "dev"
links = [
  "https://git.komo.do/komodo/-/packages/container/core"
]
repo = "mbecker20/komodo"
branch = "1.16.12"
pre_build.command = """
docker buildx create --name builder --use --bootstrap
"""
dockerfile_path = "bin/core/multi-arch.Dockerfile"
image_registry.domain = "git.komo.do"
image_registry.account = "mbecker20"
image_registry.organization = "komodo"
extra_args = [
  "--platform linux/amd64,linux/arm64",
  "--builder builder"
]
build_args = """
  REGISTRY_AND_NAMESPACE = git.komo.do/komodo
  BINARIES_TAG = latest-dev
"""

##

[[build]]
name = "komodo-periphery-dev"
tags = ["dev", "periphery"]
[build.config]
builder = "x86_64-builder"
version = "1.16.12"
auto_increment_version = false
image_name = "periphery"
image_tag = "dev"
links = [
  "https://git.komo.do/komodo/-/packages/container/core"
]
repo = "mbecker20/komodo"
branch = "1.16.12"
pre_build.command = """
docker buildx create --name builder --use --bootstrap
"""
dockerfile_path = "bin/periphery/multi-arch.Dockerfile"
image_registry.domain = "git.komo.do"
image_registry.account = "mbecker20"
image_registry.organization = "komodo"
extra_args = [
  "--platform linux/amd64,linux/arm64",
  "--builder builder"
]
build_args = """
  REGISTRY_AND_NAMESPACE = git.komo.do/komodo
  BINARIES_TAG = latest-dev
"""

##

[[procedure]]
name = "build-dev"
tags = ["dev"]

[[procedure.config.stage]]
name = "Build Binaries"
enabled = true
executions = [
  { execution.type = "BatchRunBuild", execution.params.pattern = "komodo-binaries-dev-*", enabled = true }
]

##

[[resource_sync]]
name = "dev"
tags = ["dev"]
[resource_sync.config]
git_provider = "git.komo.do"
repo = "komodo/build"
git_account = "mbecker20"
resource_path = ["dev.toml"]
managed = true
match_tags = ["dev"]