[[build]]
name = "komodo-binaries-dev-aarch64"
tags = ["dev", "binaries", "aarch64"]
[build.config]
builder = "aarch64-builder"
version = "1.17.0"
auto_increment_version = false
image_name = "binaries"
image_tag = "dev-aarch64"
links = [
  "https://git.komo.do/moghtech/-/packages/container/binaries"
]
repo = "moghtech/komodo"
branch = "1.17.0"
dockerfile_path = "bin/binaries.Dockerfile"
image_registry.domain = "ghcr.io"
image_registry.account = "mbecker20"
image_registry.organization = "moghtech"

##

[[build]]
name = "komodo-binaries-dev-x86_64"
tags = ["dev", "binaries", "x86_64"]
[build.config]
builder = "x86_64-builder"
version = "1.17.0"
auto_increment_version = false
image_name = "binaries"
image_tag = "dev-x86_64"
links = [
  "https://git.komo.do/moghtech/-/packages/container/binaries"
]
repo = "moghtech/komodo"
branch = "1.17.0"
dockerfile_path = "bin/binaries.Dockerfile"
image_registry.domain = "ghcr.io"
image_registry.account = "mbecker20"
image_registry.organization = "moghtech"

##

[[build]]
name = "komodo-core-dev"
tags = ["dev", "core"]
[build.config]
builder = "x86_64-builder"
version = "1.17.0"
auto_increment_version = false
image_name = "core"
image_tag = "dev"
links = [
  "https://git.komo.do/moghtech/-/packages/container/core"
]
repo = "moghtech/komodo"
branch = "1.17.0"
pre_build.command = """
docker buildx create --name builder --use --bootstrap
"""
dockerfile_path = "bin/core/multi-arch.Dockerfile"
image_registry.domain = "ghcr.io"
image_registry.account = "mbecker20"
image_registry.organization = "moghtech"
extra_args = [
  "--platform linux/amd64,linux/arm64",
  "--builder builder"
]
build_args = """
  BINARIES_IMAGE = ghcr.io/moghtech/binaries:latest-dev
  FRONTEND_IMAGE = ghcr.io/moghtech/frontend:latest-dev
"""

##

[[build]]
name = "komodo-frontend-dev"
tags = ["dev", "frontend"]
[build.config]
builder = "x86_64-builder"
version = "1.17.0"
auto_increment_version = false
image_name = "frontend"
image_tag = "dev"
links = [
  "https://git.komo.do/moghtech/-/packages/container/frontend"
]
repo = "moghtech/komodo"
branch = "1.17.0"
dockerfile_path = "frontend/Dockerfile"
image_registry.domain = "ghcr.io"
image_registry.account = "mbecker20"
image_registry.organization = "moghtech"

##

[[build]]
name = "komodo-periphery-dev"
tags = ["dev", "periphery"]
[build.config]
builder = "x86_64-builder"
version = "1.17.0"
auto_increment_version = false
image_name = "periphery"
image_tag = "dev"
links = [
  "https://git.komo.do/moghtech/-/packages/container/core"
]
repo = "moghtech/komodo"
branch = "1.17.0"
pre_build.command = """
docker buildx create --name builder --use --bootstrap
"""
dockerfile_path = "bin/periphery/multi-arch.Dockerfile"
image_registry.domain = "ghcr.io"
image_registry.account = "mbecker20"
image_registry.organization = "moghtech"
extra_args = [
  "--platform linux/amd64,linux/arm64",
  "--builder builder"
]
build_args = """
  BINARIES_IMAGE = ghcr.io/moghtech/binaries:latest-dev
"""

##

[[repo]]
name = "upload-binaries-dev"
tags = ["dev", "binaries"]
[repo.config]
builder = "local"
git_provider = "git.komo.do"
repo = "moghtech/build"
on_clone.command = """
bash ./upload-binaries.sh [[KOMODO_DEV_TAG]] ghcr.io/moghtech/binaries:latest-dev [[KOMODO_DEV_VERSION]] [[KOMODO_GIT_TOKEN]]
"""

##

[[procedure]]
name = "build-dev"
tags = ["dev"]

[[procedure.config.stage]]
name = "Build Binaries + Frontend"
enabled = true
executions = [
  { execution.type = "RunBuild", execution.params.build = "komodo-binaries-dev-x86_64", enabled = true },
  { execution.type = "RunBuild", execution.params.build = "komodo-binaries-dev-aarch64", enabled = true },
  { execution.type = "RunBuild", execution.params.build = "komodo-frontend-dev", enabled = true }
]

[[procedure.config.stage]]
name = "Build Multi Arch + Upload Binaries"
enabled = true
executions = [
  { execution.type = "RunBuild", execution.params.build = "komodo-core-dev", enabled = true },
  { execution.type = "RunBuild", execution.params.build = "komodo-periphery-dev", enabled = true },
  { execution.type = "BuildRepo", execution.params.repo = "upload-binaries-dev", enabled = true }
]

##

[[action]]
name = "publish-dev"
tags = ["dev"]
[action.config]
file_contents = """
const BRANCH = "1.17.0";
const VERSION = "1.17.0";
const TAG = "dev1";

await komodo.write("UpdateVariableValue", {
  name: "KOMODO_DEV_VERSION",
  value: VERSION,
});
console.log("Updated KOMODO_DEV_VERSION to", VERSION);

await komodo.write("UpdateVariableValue", {
  name: "KOMODO_DEV_TAG",
  value: TAG,
});
console.log("Updated KOMODO_DEV_TAG to", TAG);

const builds = await komodo.read("ListBuilds", { query: { tags: ["dev"] } });

for (const build of builds) {
  await komodo.write("UpdateBuild", {
    id: build.id,
    config: { version: VERSION as any, branch: BRANCH },
  });
  console.log("Updated", build.name);
}

await komodo.write("CommitSync", { sync: "dev" });
console.log("Committed changes to 'dev' Sync");

await komodo.execute("RunProcedure", { procedure: "build-dev" });
console.log("Launched 'build-dev' Procedure");
"""

##

[[resource_sync]]
name = "dev"
tags = ["dev"]
[resource_sync.config]
git_provider = "git.komo.do"
repo = "moghtech/build"
git_account = "mbecker20"
resource_path = ["dev.toml"]
managed = true
match_tags = ["dev"]